import type { VehicleCategory } from './scheduler'

export interface ServicePricingDefault {
  basePrice:      number
  estimatedHours: number
}

// National-average mobile detailing prices (2024).
// Sources: MobileXperts survey, IDA pricing guides, Thumbtack / Angi published ranges.
// Sedan is the baseline; SUV/truck/van add ~25-40%; specialty categories priced individually.
export const DETAILER_PRICING_DEFAULTS: Record<string, Record<VehicleCategory, ServicePricingDefault>> = {
  'Basic Wash': {
    sedan:      { basePrice:  40, estimatedHours: 0.5 },
    suv:        { basePrice:  50, estimatedHours: 0.75 },
    truck:      { basePrice:  50, estimatedHours: 0.75 },
    van:        { basePrice:  55, estimatedHours: 0.75 },
    motorcycle: { basePrice:  25, estimatedHours: 0.5 },
    boat:       { basePrice:  75, estimatedHours: 1.0 },
    rv:         { basePrice: 100, estimatedHours: 1.5 },
    plane:      { basePrice:  75, estimatedHours: 1.0 },
    other:      { basePrice:  45, estimatedHours: 0.5 },
  },
  'Full Detail': {
    sedan:      { basePrice: 175, estimatedHours: 3.5 },
    suv:        { basePrice: 225, estimatedHours: 4.5 },
    truck:      { basePrice: 225, estimatedHours: 4.5 },
    van:        { basePrice: 250, estimatedHours: 5.0 },
    motorcycle: { basePrice:  75, estimatedHours: 1.5 },
    boat:       { basePrice: 300, estimatedHours: 5.0 },
    rv:         { basePrice: 450, estimatedHours: 7.0 },
    plane:      { basePrice: 350, estimatedHours: 5.5 },
    other:      { basePrice: 200, estimatedHours: 4.0 },
  },
  'Interior Detail': {
    sedan:      { basePrice: 100, estimatedHours: 2.0 },
    suv:        { basePrice: 125, estimatedHours: 2.5 },
    truck:      { basePrice: 125, estimatedHours: 2.5 },
    van:        { basePrice: 150, estimatedHours: 3.0 },
    motorcycle: { basePrice:   0, estimatedHours: 0.0 },
    boat:       { basePrice: 150, estimatedHours: 2.5 },
    rv:         { basePrice: 250, estimatedHours: 4.0 },
    plane:      { basePrice: 200, estimatedHours: 3.0 },
    other:      { basePrice: 110, estimatedHours: 2.0 },
  },
  'Exterior Detail': {
    sedan:      { basePrice:  90, estimatedHours: 1.5 },
    suv:        { basePrice: 115, estimatedHours: 2.0 },
    truck:      { basePrice: 115, estimatedHours: 2.0 },
    van:        { basePrice: 130, estimatedHours: 2.5 },
    motorcycle: { basePrice:  60, estimatedHours: 1.0 },
    boat:       { basePrice: 175, estimatedHours: 2.5 },
    rv:         { basePrice: 250, estimatedHours: 4.0 },
    plane:      { basePrice: 200, estimatedHours: 3.0 },
    other:      { basePrice: 100, estimatedHours: 1.5 },
  },
  'Paint Correction': {
    sedan:      { basePrice: 400, estimatedHours: 6.0 },
    suv:        { basePrice: 500, estimatedHours: 7.5 },
    truck:      { basePrice: 500, estimatedHours: 7.5 },
    van:        { basePrice: 550, estimatedHours: 8.0 },
    motorcycle: { basePrice: 200, estimatedHours: 3.0 },
    boat:       { basePrice: 600, estimatedHours: 8.0 },
    rv:         { basePrice: 900, estimatedHours: 12.0 },
    plane:      { basePrice: 700, estimatedHours: 10.0 },
    other:      { basePrice: 450, estimatedHours: 6.5 },
  },
  'Ceramic Coating (1 Year)': {
    sedan:      { basePrice: 300,  estimatedHours: 4.0 },
    suv:        { basePrice: 375,  estimatedHours: 5.0 },
    truck:      { basePrice: 375,  estimatedHours: 5.0 },
    van:        { basePrice: 425,  estimatedHours: 5.5 },
    motorcycle: { basePrice: 175,  estimatedHours: 2.5 },
    boat:       { basePrice: 500,  estimatedHours: 6.0 },
    rv:         { basePrice: 750,  estimatedHours: 9.0 },
    plane:      { basePrice: 600,  estimatedHours: 7.5 },
    other:      { basePrice: 325,  estimatedHours: 4.5 },
  },
  'Ceramic Coating (3 Year)': {
    sedan:      { basePrice: 600,  estimatedHours: 5.5 },
    suv:        { basePrice: 750,  estimatedHours: 6.5 },
    truck:      { basePrice: 750,  estimatedHours: 6.5 },
    van:        { basePrice: 850,  estimatedHours: 7.5 },
    motorcycle: { basePrice: 350,  estimatedHours: 3.5 },
    boat:       { basePrice: 1000, estimatedHours: 8.0 },
    rv:         { basePrice: 1500, estimatedHours: 12.0 },
    plane:      { basePrice: 1200, estimatedHours: 10.0 },
    other:      { basePrice: 650,  estimatedHours: 6.0 },
  },
  'Ceramic Coating (5 Year)': {
    sedan:      { basePrice: 1000, estimatedHours: 7.0 },
    suv:        { basePrice: 1250, estimatedHours: 8.5 },
    truck:      { basePrice: 1250, estimatedHours: 8.5 },
    van:        { basePrice: 1400, estimatedHours: 9.5 },
    motorcycle: { basePrice:  600, estimatedHours: 4.5 },
    boat:       { basePrice: 1600, estimatedHours: 10.0 },
    rv:         { basePrice: 2500, estimatedHours: 16.0 },
    plane:      { basePrice: 2000, estimatedHours: 13.0 },
    other:      { basePrice: 1100, estimatedHours: 8.0 },
  },
  'Headlight Restoration': {
    sedan:      { basePrice:  75, estimatedHours: 1.0 },
    suv:        { basePrice:  75, estimatedHours: 1.0 },
    truck:      { basePrice:  75, estimatedHours: 1.0 },
    van:        { basePrice:  75, estimatedHours: 1.0 },
    motorcycle: { basePrice:  50, estimatedHours: 0.75 },
    boat:       { basePrice:  75, estimatedHours: 1.0 },
    rv:         { basePrice:  90, estimatedHours: 1.25 },
    plane:      { basePrice:  90, estimatedHours: 1.25 },
    other:      { basePrice:  75, estimatedHours: 1.0 },
  },
  'Engine Bay Cleaning': {
    sedan:      { basePrice:  75, estimatedHours: 1.25 },
    suv:        { basePrice:  90, estimatedHours: 1.5 },
    truck:      { basePrice:  90, estimatedHours: 1.5 },
    van:        { basePrice: 100, estimatedHours: 1.75 },
    motorcycle: { basePrice:  50, estimatedHours: 1.0 },
    boat:       { basePrice:  90, estimatedHours: 1.5 },
    rv:         { basePrice: 125, estimatedHours: 2.0 },
    plane:      { basePrice: 100, estimatedHours: 1.5 },
    other:      { basePrice:  80, estimatedHours: 1.25 },
  },
  'Carpet & Upholstery Shampoo': {
    sedan:      { basePrice: 100, estimatedHours: 2.0 },
    suv:        { basePrice: 125, estimatedHours: 2.5 },
    truck:      { basePrice: 110, estimatedHours: 2.0 },
    van:        { basePrice: 150, estimatedHours: 3.0 },
    motorcycle: { basePrice:   0, estimatedHours: 0.0 },
    boat:       { basePrice: 150, estimatedHours: 2.5 },
    rv:         { basePrice: 250, estimatedHours: 4.0 },
    plane:      { basePrice: 175, estimatedHours: 2.5 },
    other:      { basePrice: 110, estimatedHours: 2.0 },
  },
  'Leather Treatment': {
    sedan:      { basePrice:  75, estimatedHours: 1.25 },
    suv:        { basePrice:  90, estimatedHours: 1.5 },
    truck:      { basePrice:  90, estimatedHours: 1.5 },
    van:        { basePrice: 100, estimatedHours: 1.75 },
    motorcycle: { basePrice:  40, estimatedHours: 0.75 },
    boat:       { basePrice: 100, estimatedHours: 1.75 },
    rv:         { basePrice: 175, estimatedHours: 3.0 },
    plane:      { basePrice: 125, estimatedHours: 2.0 },
    other:      { basePrice:  80, estimatedHours: 1.25 },
  },
  'Pet Hair & Odor Removal': {
    sedan:      { basePrice: 100, estimatedHours: 1.5 },
    suv:        { basePrice: 125, estimatedHours: 2.0 },
    truck:      { basePrice: 125, estimatedHours: 2.0 },
    van:        { basePrice: 150, estimatedHours: 2.5 },
    motorcycle: { basePrice:   0, estimatedHours: 0.0 },
    boat:       { basePrice: 125, estimatedHours: 2.0 },
    rv:         { basePrice: 200, estimatedHours: 3.5 },
    plane:      { basePrice: 150, estimatedHours: 2.5 },
    other:      { basePrice: 110, estimatedHours: 1.75 },
  },
  'Boat Detailing': {
    sedan:      { basePrice:   0, estimatedHours: 0.0 },
    suv:        { basePrice:   0, estimatedHours: 0.0 },
    truck:      { basePrice:   0, estimatedHours: 0.0 },
    van:        { basePrice:   0, estimatedHours: 0.0 },
    motorcycle: { basePrice:   0, estimatedHours: 0.0 },
    boat:       { basePrice: 350, estimatedHours: 5.0 },
    rv:         { basePrice:   0, estimatedHours: 0.0 },
    plane:      { basePrice:   0, estimatedHours: 0.0 },
    other:      { basePrice: 300, estimatedHours: 4.5 },
  },
  'RV Detailing': {
    sedan:      { basePrice:   0, estimatedHours: 0.0 },
    suv:        { basePrice:   0, estimatedHours: 0.0 },
    truck:      { basePrice:   0, estimatedHours: 0.0 },
    van:        { basePrice:   0, estimatedHours: 0.0 },
    motorcycle: { basePrice:   0, estimatedHours: 0.0 },
    boat:       { basePrice:   0, estimatedHours: 0.0 },
    rv:         { basePrice: 500, estimatedHours: 8.0 },
    plane:      { basePrice:   0, estimatedHours: 0.0 },
    other:      { basePrice: 400, estimatedHours: 6.5 },
  },
  'Other': {
    sedan:      { basePrice: 75, estimatedHours: 1.5 },
    suv:        { basePrice: 90, estimatedHours: 2.0 },
    truck:      { basePrice: 90, estimatedHours: 2.0 },
    van:        { basePrice: 100, estimatedHours: 2.0 },
    motorcycle: { basePrice: 50, estimatedHours: 1.0 },
    boat:       { basePrice: 100, estimatedHours: 2.0 },
    rv:         { basePrice: 150, estimatedHours: 3.0 },
    plane:      { basePrice: 125, estimatedHours: 2.5 },
    other:      { basePrice: 80,  estimatedHours: 1.5 },
  },
}
