'use client'

// Self-contained contact-preference card. Drops onto a customer or work-order
// page with just a customerId and fetches its own state, so no parent page has
// to learn about these columns or thread them through props.
//
// SuppressionBadge at the bottom is the read-only companion for list rows and
// headers — both use suppressionLabel() from the shared gate, so the wording a
// mechanic reads is generated by the same module the senders enforce.

import { useCallback, useEffect, useState } from 'react'
import { suppressionLabel, type ContactSuppression } from '@/lib/customer-contact'

const HD_ORANGE = '#E85D24'

const inputStyle = { background: '#162030', border: '1px solid #1e3040' }

interface Props {
  customerId: string
  canEdit:    boolean
}

interface PrefsRow {
  no_email:                 boolean
  no_sms:                   boolean
  contact_prefs_note:       string | null
  contact_prefs_updated_at: string | null
}

export default function ContactPreferences({ customerId, canEdit }: Props) {
  const [prefs,   setPrefs]   = useState<PrefsRow | null>(null)
  const [note,    setNote]    = useState('')
  const [loading, setLoading] = useState(true)
  const [saving,  setSaving]  = useState(false)
  const [saved,   setSaved]   = useState(false)
  const [error,   setError]   = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false

    async function load() {
      setLoading(true); setError(null)
      try {
        const res = await fetch(`/api/customers/${customerId}/contact-prefs`)
        if (!res.ok) {
          const json = await res.json().catch(() => ({}))
          throw new Error(json.error ?? 'Could not load contact preferences')
        }
        const json = await res.json()
        if (cancelled) return
        setPrefs(json.prefs)
        setNote(json.prefs?.contact_prefs_note ?? '')
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : 'Could not load contact preferences')
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    load()
    // Guards against a customerId change resolving out of order and writing a
    // stale customer's preferences into the card.
    return () => { cancelled = true }
  }, [customerId])

  const save = useCallback(async (patch: Partial<PrefsRow>) => {
    setSaving(true); setSaved(false); setError(null)
    try {
      const res = await fetch(`/api/customers/${customerId}/contact-prefs`, {
        method:  'PUT',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify(patch),
      })
      const json = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(json.error ?? 'Save failed')
      // Adopt the server's row rather than the optimistic patch — the server
      // stamps contact_prefs_updated_at and normalises the note, and the card
      // should show what was actually stored.
      setPrefs(json.prefs)
      setNote(json.prefs?.contact_prefs_note ?? '')
      setSaved(true)
      setTimeout(() => setSaved(false), 3000)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Save failed')
      // Re-read on failure so a rejected toggle does not leave the checkbox
      // showing a state the database never accepted.
      try {
        const res = await fetch(`/api/customers/${customerId}/contact-prefs`)
        if (res.ok) {
          const json = await res.json()
          setPrefs(json.prefs)
          setNote(json.prefs?.contact_prefs_note ?? '')
        }
      } catch { /* leave the error message standing */ }
    } finally {
      setSaving(false)
    }
  }, [customerId])

  const card = 'rounded-xl p-4 sm:p-5'
  const cardStyle = { background: '#111b28', border: '1px solid #1e3040' }

  if (loading) {
    return (
      <div className={card} style={cardStyle}>
        <p className="text-sm" style={{ color: 'rgba(255,255,255,0.35)' }}>Loading contact preferences…</p>
      </div>
    )
  }

  if (!prefs) {
    return (
      <div className={card} style={cardStyle}>
        <p className="text-sm text-red-400">{error ?? 'Contact preferences unavailable'}</p>
      </div>
    )
  }

  // The API returns the raw customers columns (contact_prefs_note); the shared
  // gate's interface names that field `note`. Mapped here rather than renaming
  // either side — the column name belongs to the table, the short name belongs
  // to the gate, and one adapter beats leaking either into the other.
  const suppression: ContactSuppression = {
    no_email: prefs.no_email,
    no_sms:   prefs.no_sms,
    note:     prefs.contact_prefs_note,
  }
  const label = suppressionLabel(suppression)

  return (
    <div className={card} style={cardStyle}>
      <div className="flex items-start justify-between gap-3 mb-3">
        <div>
          <h3 className="text-sm font-semibold text-white">Contact Preferences</h3>
          <p className="text-xs mt-0.5" style={{ color: 'rgba(255,255,255,0.35)' }}>
            Stops automated texts and emails. Does not affect calls you place yourself.
          </p>
        </div>
        {label && <SuppressionBadge suppression={suppression} />}
      </div>

      <div className="space-y-3">
        <label className={`flex items-center justify-between gap-3 ${canEdit ? 'cursor-pointer' : ''}`}>
          <div>
            <span className="text-sm font-semibold text-white">Do not send SMS</span>
            <p className="text-xs" style={{ color: 'rgba(255,255,255,0.35)' }}>No review requests, reminders, or invoice texts.</p>
          </div>
          <input
            type="checkbox"
            checked={prefs.no_sms}
            disabled={!canEdit || saving}
            onChange={e => save({ no_sms: e.target.checked })}
            className="w-5 h-5 shrink-0"
            style={{ accentColor: HD_ORANGE, opacity: canEdit ? 1 : 0.5 }}
          />
        </label>

        <label className={`flex items-center justify-between gap-3 ${canEdit ? 'cursor-pointer' : ''}`}>
          <div>
            <span className="text-sm font-semibold text-white">Do not send email</span>
            <p className="text-xs" style={{ color: 'rgba(255,255,255,0.35)' }}>No emailed invoices, receipts, or reports.</p>
          </div>
          <input
            type="checkbox"
            checked={prefs.no_email}
            disabled={!canEdit || saving}
            onChange={e => save({ no_email: e.target.checked })}
            className="w-5 h-5 shrink-0"
            style={{ accentColor: HD_ORANGE, opacity: canEdit ? 1 : 0.5 }}
          />
        </label>

        <div>
          <label className="block text-xs uppercase tracking-widest mb-1.5" style={{ color: 'rgba(255,255,255,0.4)' }}>
            Note (optional)
          </label>
          <textarea
            value={note}
            disabled={!canEdit || saving}
            onChange={e => setNote(e.target.value)}
            // Saved on blur rather than per-keystroke: this is a rarely-edited
            // free-text field and a PUT per character would be pure noise.
            onBlur={() => { if (canEdit && note !== (prefs.contact_prefs_note ?? '')) save({ contact_prefs_note: note }) }}
            rows={2}
            placeholder="e.g. asked to be called only — no texts"
            className="w-full px-3 py-2.5 rounded-lg text-base sm:text-sm text-white placeholder-white/20 resize-y"
            style={inputStyle}
          />
        </div>
      </div>

      {error && <p className="text-sm text-red-400 mt-3">{error}</p>}
      {saved && <p className="text-sm mt-3" style={{ color: '#22C55E' }}>Saved</p>}

      {prefs.contact_prefs_updated_at && (
        <p className="text-xs mt-3" style={{ color: 'rgba(255,255,255,0.3)' }}>
          Last updated {new Date(prefs.contact_prefs_updated_at).toLocaleDateString()}
        </p>
      )}
    </div>
  )
}

/**
 * Read-only pill for customer lists, work-order headers and invoice screens.
 * Renders nothing when the customer is not suppressed, so it can be dropped in
 * unconditionally without the caller checking first.
 */
export function SuppressionBadge({ suppression }: { suppression: ContactSuppression | null | undefined }) {
  const label = suppressionLabel(suppression)
  if (!label) return null

  return (
    <span
      className="inline-flex items-center shrink-0 px-2 py-0.5 rounded-md text-xs font-semibold whitespace-nowrap"
      style={{ background: 'rgba(232,93,36,0.12)', color: HD_ORANGE, border: `1px solid rgba(232,93,36,0.3)` }}
      title={suppression?.note ?? undefined}
    >
      {label}
    </span>
  )
}
