// Source: TK Operator Document TK 40933-8-CH Rev 15

export type TKSeverity = 'ok_to_run' | 'check_specified' | 'immediate_action'

export interface TKAlarmEntry {
  description:    string
  severity:       TKSeverity
  operatorAction: string
}

export const TK_ALARM_CODES: Record<string, TKAlarmEntry> = {
  "00": { description: "No Alarms Exist", severity: "ok_to_run", operatorAction: "No action required." },
  "02": { description: "Check Evaporator Coil Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "03": { description: "Check Control Return Air Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "04": { description: "Check Control Discharge Air Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "05": { description: "Check Ambient Temp Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "06": { description: "Check Coolant Temp Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "07": { description: "Check Engine RPM Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "08": { description: "Unit Running on Coil Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "09": { description: "High Evaporator Temperature", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "10": { description: "High Discharge Pressure or Temperature", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "11": { description: "Unit or Zone Controlling on Alternate Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "12": { description: "Sensor or Digital Input Shutdown", severity: "immediate_action", operatorAction: "Unit/zone cannot operate and is shut down. Repair immediately." },
  "13": { description: "Sensor Check", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "14": { description: "Defrost Terminated by Time", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "15": { description: "Check Glow Plugs or Intake Air Heater", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "16": { description: "Manual Start Not Completed", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "17": { description: "Engine Failed to Crank", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "18": { description: "High Engine Coolant Temperature", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "19": { description: "Low Engine Oil Pressure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "20": { description: "Engine Failed to Start", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "21": { description: "Cooling Cycle Check", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "22": { description: "Heating Cycle Check", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "23": { description: "Cooling Cycle Fault", severity: "immediate_action", operatorAction: "Unit/zone cannot operate and is shut down. Repair immediately." },
  "24": { description: "Heating Cycle Fault", severity: "immediate_action", operatorAction: "Unit/zone cannot operate and is shut down. Repair immediately." },
  "25": { description: "Alternator Check", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "26": { description: "Check Refrigeration Capacity", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "27": { description: "Vapor Motor RPM High", severity: "immediate_action", operatorAction: "Unit cannot operate and is shut down. Repair immediately." },
  "28": { description: "Pretrip or Self Check Abort", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "29": { description: "Defrost Damper Circuit Check", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "30": { description: "Defrost Damper Stuck Closed", severity: "immediate_action", operatorAction: "Unit/zone cannot operate and is shut down. Repair immediately." },
  "31": { description: "Check Oil Pressure Switch", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "32": { description: "Refrigeration Capacity Low", severity: "immediate_action", operatorAction: "Unit/zone cannot operate and is shut down. Repair immediately." },
  "33": { description: "Check Engine RPM", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "34": { description: "Check Modulation Circuit", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "35": { description: "Check Run Relay Circuit", severity: "immediate_action", operatorAction: "Unit cannot operate and is shut down. Repair immediately." },
  "36": { description: "Electric Motor Failed to Run", severity: "immediate_action", operatorAction: "Unit cannot operate and is shut down. Repair immediately. Switch to Diesel Mode." },
  "37": { description: "Check Engine Coolant Level", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "38": { description: "Electric Phase Reversed", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "39": { description: "Check Water Valve Circuit", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "40": { description: "Check High Speed Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "41": { description: "Check Engine Coolant Temp", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "42": { description: "Unit Forced to Low Speed", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "43": { description: "Unit Forced to Low Speed Modulation", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "44": { description: "Check Fuel System", severity: "check_specified", operatorAction: "Add fuel as necessary. Otherwise, report alarm at end of day." },
  "45": { description: "Check Hot Gas or Hot Gas Bypass Circuit", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "46": { description: "Check Air Flow", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "47": { description: "Remote Sensor Shutdown", severity: "immediate_action", operatorAction: "Unit/zone cannot operate and is shut down. Repair immediately." },
  "48": { description: "Check Belts or Clutch", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "49": { description: "Check Spare Sensor 1", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "50": { description: "Reset Clock", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "51": { description: "Check Shutdown Circuit", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "52": { description: "Check Heat Circuit", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "53": { description: "Check Economizer Valve Circuit", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "54": { description: "Test Mode Timeout", severity: "ok_to_run", operatorAction: "Clear alarm and restart unit." },
  "55": { description: "Check Engine Speeds", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "56": { description: "Check Evaporator Fan Low Speed", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "57": { description: "Check Evaporator Fan High Speed", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "61": { description: "Low Battery Voltage", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "62": { description: "Ammeter Out of Calibration", severity: "immediate_action", operatorAction: "Unit cannot operate and is shut down. Repair immediately." },
  "63": { description: "Engine or Vapor Motor Stopped", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "64": { description: "Pretrip Reminder", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "65": { description: "Abnormal Temperature Differential", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "66": { description: "Low Engine Oil Level", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "67": { description: "Check Liquid Line Solenoid Circuit", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "68": { description: "Internal Controller Fault Code", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "70": { description: "Hourmeter Failure", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "71": { description: "Hourmeter 4 Exceeds Set Time Limit", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "72": { description: "Hourmeter 5 Exceeds Set Time Limit", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "73": { description: "Hourmeter 6 Exceeds Set Time Limit", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "74": { description: "Controller Reset to Defaults", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "75": { description: "Controller RAM Failure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "76": { description: "Controller EPROM Failure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "77": { description: "Controller EPROM Checksum Failure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "78": { description: "Data Log EPROM Failure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "79": { description: "Internal Data Logger Overflow", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "80": { description: "Check Compressor Temp Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "81": { description: "High Compressor Temp", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "82": { description: "High Compressor Temp Shutdown", severity: "immediate_action", operatorAction: "Unit cannot operate and is shut down. Repair immediately." },
  "83": { description: "Low Engine Coolant Temp", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "84": { description: "Restart Null", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "85": { description: "Forced Unit Operation", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "86": { description: "Check Discharge Pressure Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "87": { description: "Check Suction Pressure Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "89": { description: "Check Electronic Throttling Valve ETV Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "90": { description: "Electric Overload", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "91": { description: "Check Electric Ready Input", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "92": { description: "Sensor Grades Not Set", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "93": { description: "Low Compressor Suction Pressure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "94": { description: "Check Loader 1 Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "95": { description: "Check Loader 2 Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "96": { description: "Low Fuel Level", severity: "ok_to_run", operatorAction: "Add fuel as required." },
  "97": { description: "Failed Remote Return Air Sensor", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "98": { description: "Check Fuel Level Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "99": { description: "High Compressor Pressure Ratio", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "100": { description: "Heater Fan Failure", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "101": { description: "Controlling on Evap Coil Outlet Temp", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "102": { description: "Low Evaporator Coil Temperature", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "103": { description: "Low Heater Fuel Level", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "104": { description: "Check Remote Fan Speed", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "105": { description: "Check Receiver Tank Press Sol Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "106": { description: "Check Purge Valve Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "107": { description: "Check Condenser Inlet Sol Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "108": { description: "Door Open Timeout", severity: "check_specified", operatorAction: "Close doors. Report alarm at end of day." },
  "110": { description: "Check Suction Line Sol Circuit", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "111": { description: "Unit Not Configured Correctly", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "112": { description: "Check Remote Fans", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "113": { description: "Check Electric Heat Circuit", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "114": { description: "Multiple Alarms - Can Not Run", severity: "immediate_action", operatorAction: "Unit/zone cannot operate and is shut down. Repair immediately." },
  "115": { description: "Check High Pressure Cut Out Switch", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "116": { description: "Check High Pressure Cut In Switch", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "117": { description: "Auto Switch from Diesel to Electric", severity: "ok_to_run", operatorAction: "Normal operation — does not affect performance." },
  "118": { description: "Auto Switch from Electric to Diesel", severity: "ok_to_run", operatorAction: "Normal operation — does not affect performance." },
  "120": { description: "Check Alternator Excite Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "121": { description: "Check PMW Liquid Injection Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "122": { description: "Check Diesel/Electric Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "123": { description: "Check Evap Coil Inlet Temp Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "124": { description: "Check Evap Coil Outlet Temp Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "125": { description: "Check Tank Level Sensor", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "126": { description: "Check Back Pressure Regulator", severity: "check_specified", operatorAction: "Manually monitor load temperature. Report this alarm at the end of the day." },
  "127": { description: "Setpoint Not Entered", severity: "check_specified", operatorAction: "Be sure setpoint is adjusted to required temperature." },
  "128": { description: "Engine Run Time Maintenance Reminder 1 — Service Due", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "129": { description: "Engine Run Time Maintenance Reminder 2", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "130": { description: "Electric Run Time Maintenance Reminder 1", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "131": { description: "Electric Run Time Maintenance Reminder 2", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "132": { description: "Total Unit Run Time Maintenance Reminder 1", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "133": { description: "Total Unit Run Time Maintenance Reminder 2", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "134": { description: "Controller Power On Hours", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "135": { description: "Check Spare Digital Inputs", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "136": { description: "Check Spare Digital Outputs", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "137": { description: "Check Damper Motor Heater Output", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "138": { description: "Log DAS Real Time Clock Battery Failure", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "139": { description: "Abort Evacuation Mode", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "141": { description: "Auto Switch Diesel to Electric Disabled", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "142": { description: "Check Thermax Valve", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "143": { description: "Check Remote Drain Hose Heater Output", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "144": { description: "Lost CAN Communications to Expansion Module", severity: "immediate_action", operatorAction: "Unit cannot operate and is shut down. Repair immediately." },
  "145": { description: "Lost Controller ON Feedback Signal", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "146": { description: "Software Version Mismatch", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "147": { description: "Check Multi-Temp Fan Speed Control Output", severity: "check_specified", operatorAction: "Manually monitor load temperature. Report this alarm at the end of the day." },
  "148": { description: "Auto Switch Electric to Diesel Disabled", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "149": { description: "Alarm Not Identified", severity: "immediate_action", operatorAction: "If unit/zone is shut down repair immediately. Otherwise, report alarm at end of day." },
  "150": { description: "Sensor Out of Range Low", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "151": { description: "Sensor Out of Range High", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "152": { description: "DAS Failed Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "153": { description: "Expansion Module Flash Load Failure", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "154": { description: "Low Suction Pressure Switch Failure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "155": { description: "Lost CAN Communications to HMI", severity: "immediate_action", operatorAction: "Unit cannot operate and is shut down. Repair immediately." },
  "156": { description: "Check Suction/Liquid Heat Exchanger Bypass Valve", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "157": { description: "OptiSet Plus Profile Mismatch", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "158": { description: "Primary Software Failed to Load", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "159": { description: "Check Battery Condition", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "160": { description: "Lost CAN Communications to Radio Expansion Board", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "161": { description: "Log DAS Real Time Clock Invalid", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "163": { description: "Emission Control Failure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "165": { description: "Low Engine Power Available", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "175": { description: "Check Electronic Expansion Valve", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "176": { description: "Check Evaporator Pressure Sensor", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "177": { description: "Check CO2 Tank Pressure Sensor", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "178": { description: "Low CO2 Fuel Level", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "180": { description: "TriPac Compressor Alarm", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "188": { description: "Log DAS Microprocessor Fault", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "203": { description: "Check Display Return Air Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "204": { description: "Check Display Discharge Air Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "216": { description: "Check DAS Digital Inputs", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "233": { description: "REB Switching Off Conservative to Full", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "234": { description: "Check Relative Humidity Sensor Circuit", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "235": { description: "High Engine Coolant Temperature Check", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "250": { description: "DAS Clock Time Reset", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "251": { description: "Check Radio Expansion Board Configuration", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "252": { description: "Check Auto Fresh Air Exchange Circuit", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "253": { description: "REB On Back Up Battery Alarms Disabled", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "254": { description: "Check Auxiliary Coolant Temp Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "500": { description: "Check Host Evaporator Blower Low Speed", severity: "check_specified", operatorAction: "Not implemented." },
  "501": { description: "Check Host Evaporator Blower High Speed", severity: "check_specified", operatorAction: "Not implemented." },
  "505": { description: "Check Roadside Condenser Fan Motor Speed Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "506": { description: "Check Curbside Condenser Fan Motor Speed Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "507": { description: "Check Digital Scroll Output Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "508": { description: "Speed Request Communication Error", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "509": { description: "ECU Failed to Enable", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "510": { description: "ECU Run Signal Failed", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "511": { description: "Engine Wait to Start Time Delay Expired", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "512": { description: "High Compressor Suction Pressure Scroll Only", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "513": { description: "Low Compressor Suction Ratio Scroll Only", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "514": { description: "Low Compressor Discharge Pressure Scroll Only", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "515": { description: "Minimum ETV Discharge Superheat Temp Scroll", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "516": { description: "IO Controller to Application Controller Communication Failure", severity: "immediate_action", operatorAction: "The unit is no longer able to operate and has been shut down. Repair immediately." },
  "518": { description: "Generator Ground Fault", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "519": { description: "Check Battery Charger Input Power", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "520": { description: "Check Battery Charger Output Power", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "521": { description: "Battery Charger External Environmental Fault", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "522": { description: "Battery Temperature Sensor Alarm", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "523": { description: "Battery Charger Indicated Conditions", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "524": { description: "Generator Op Limit Vout to Frequency Ratio", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "525": { description: "Generator Frequency Range Fault", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "526": { description: "Generator Operational Limit Output Current", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "528": { description: "Failed J1939 CAN Communication Base Controller Charger", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "529": { description: "Check Fuel Pump Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "530": { description: "Low Pressure Differential Scroll Only", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "531": { description: "Check Economizer Pressure Sensor Scroll Only", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "538": { description: "Engine J1939 CAN Data Link Degraded", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "539": { description: "Engine J1939 CAN Data Link Failed", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "540": { description: "Illegal Engine Operating State", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "542": { description: "Battery Charger Fault Unit Forced to Low Speed", severity: "check_specified", operatorAction: "Maintenance information only. Report alarm at end of day." },
  "543": { description: "Battery Charger Internal Short", severity: "check_specified", operatorAction: "Maintenance information only. Report alarm at end of day." },
  "544": { description: "Battery Charger External Short", severity: "check_specified", operatorAction: "Maintenance information only. Report alarm at end of day." },
  "545": { description: "Battery Charger Output Voltage Exceeded Limit", severity: "check_specified", operatorAction: "Maintenance information only. Report alarm at end of day." },
  "546": { description: "Battery Charger Operating Bulk Voltage Out of Range", severity: "check_specified", operatorAction: "Maintenance information only. Report alarm at end of day." },
  "547": { description: "AC Bus Phase Loss", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "548": { description: "Battery Charger Temperature Below Operating Range", severity: "check_specified", operatorAction: "Maintenance information only. Report alarm at end of day." },
  "549": { description: "Battery Charger AC Input Overvoltage", severity: "check_specified", operatorAction: "Maintenance information only. Report alarm at end of day." },
  "550": { description: "Battery Charger Internal Overvoltage Fault", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "570": { description: "Clean EGR Soon", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "599": { description: "Engine Service Tool Connected", severity: "ok_to_run", operatorAction: "Report alarm at end of day." },
  "600": { description: "Check Crankshaft Speed Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "601": { description: "Check Camshaft Speed Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "602": { description: "Check Intake Throttle Position Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "603": { description: "Check Exhaust Pressure Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "604": { description: "Check Coolant Temp Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "605": { description: "Check Fresh Air Temp Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "607": { description: "Check Fuel Temperature Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "608": { description: "Check Rail Pressure Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "609": { description: "Check Intake Pressure Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "610": { description: "Check Atmospheric Pressure Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "611": { description: "Check Glow Plug Circuit", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "612": { description: "Check Intake Throttle Circuit", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "613": { description: "Check Injectors", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "614": { description: "Check High Pressure Fuel Pump", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "615": { description: "Rail Pressure Fault", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "616": { description: "Engine Overspeed", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "617": { description: "Internal ECU Fault", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "618": { description: "Check EGR System", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "619": { description: "ECU Main Relay Fault", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "620": { description: "No RPM Detected During Start Attempt", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "623": { description: "TRUCAN Message Timeout", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "624": { description: "Check EGR Temperature Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "625": { description: "Check Intake Air Temperature Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "626": { description: "Check Exhaust Temperature Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "642": { description: "ECU Forced Low Speed", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "699": { description: "Unknown ECU Fault", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
}

export const TK_DSR_ALARM_CODES: Record<string, Omit<TKAlarmEntry, 'severity'> & { severity: 'immediate_action' | 'check_specified' }> = {
  "P1E": { description: "Return Air Temperature Sensor Fault", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "P2E": { description: "Remote Return Air Temperature Sensor Fault", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "OL":  { description: "Electric Standby Overload", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "BAT": { description: "Low Battery Voltage", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "HP":  { description: "High Discharge Pressure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "LP":  { description: "Low Suction Pressure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "PSE": { description: "High Pressure Sensor Fault", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "TEP": { description: "Electric Standby Motor Thermal Protection Alarm", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "TP4": { description: "Power Supply Thermal Protection Alarm", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "DR1": { description: "Door 1 Open or Door Switch 1 Failure", severity: "check_specified", operatorAction: "Close door. Report alarm at end of day." },
  "DR2": { description: "Door 2 Open or Door Switch 2 Failure", severity: "check_specified", operatorAction: "Close door. Report alarm at end of day." },
  "TCO": { description: "Electronic Control Module Internal Temperature Exceeds Limit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "SOF": { description: "Microprocessor Software Failure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
  "-C-": { description: "Communications Failure Microprocessor to In-Cab Control Box", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise, report alarm at end of day." },
}

// ─── Carrier Transicold Alarm Codes ──────────────────────────────────────────
// Sourced from publicly available Carrier Transicold operator reference information.
// Not all codes apply to all unit models — verify against official documentation.

export const CARRIER_ALARM_CODES: Record<string, { description: string; severity: 'immediate_action' | 'check_specified' | 'ok_to_run'; operatorAction: string }> = {
  "1":   { description: "Low Fuel Level", severity: "check_specified", operatorAction: "Add fuel as necessary. Report alarm at end of day." },
  "2":   { description: "Low Engine Oil Level", severity: "immediate_action", operatorAction: "Check oil level immediately. Do not operate unit until oil level is corrected." },
  "3":   { description: "Low Coolant Level", severity: "immediate_action", operatorAction: "Check coolant level immediately. Do not operate unit until coolant is corrected." },
  "11":  { description: "Low Engine Oil Pressure", severity: "immediate_action", operatorAction: "Shut down unit immediately. Do not restart until oil pressure fault is found and corrected." },
  "12":  { description: "High Coolant Temperature", severity: "immediate_action", operatorAction: "Shut down unit immediately. Allow to cool. Check coolant level and cooling system before restarting." },
  "13":  { description: "High Discharge Pressure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "15":  { description: "Battery Voltage Too High", severity: "check_specified", operatorAction: "Report alarm at end of day. Check charging system." },
  "16":  { description: "Battery Voltage Too Low", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Check battery and charging system." },
  "17":  { description: "High Compressor Discharge Temperature", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "18":  { description: "Low Refrigerant Pressure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. EPA 608 certified technician required for refrigerant service." },
  "28":  { description: "Check Refrigeration System", severity: "immediate_action", operatorAction: "Unit cannot maintain temperature. Repair immediately." },
  "30":  { description: "Failed to Run Minimum Time", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "31":  { description: "Failed to Start — Auto Mode", severity: "immediate_action", operatorAction: "Unit cannot operate. Repair immediately." },
  "32":  { description: "Failed to Start — Manual", severity: "immediate_action", operatorAction: "Unit cannot operate. Repair immediately." },
  "34":  { description: "Engine Failed to Stop", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "35":  { description: "Check Starter Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "36":  { description: "Check Coolant Temperature", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "37":  { description: "Check Low Speed RPM", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "38":  { description: "Check High Speed RPM", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "39":  { description: "Check Engine RPM", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "40":  { description: "Check Glow Plugs", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "41":  { description: "Engine Stalled", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "51":  { description: "Alternator Not Charging", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Check belts and alternator immediately." },
  "53":  { description: "Box Temperature Out of Range", severity: "immediate_action", operatorAction: "Cargo at risk. Repair immediately." },
  "54":  { description: "Defrost Not Complete", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "55":  { description: "Check Defrost Air Switch", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "56":  { description: "Check Airflow", severity: "check_specified", operatorAction: "Check for airflow restrictions. Report alarm at end of day." },
  "57":  { description: "Check Remote Switch 1", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "58":  { description: "Check Remote Switch 2", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "59":  { description: "DataLogger Not Recording", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "60":  { description: "DataLogger Time Wrong", severity: "check_specified", operatorAction: "Reset DataLogger clock. Report alarm at end of day." },
  "61":  { description: "Door Open", severity: "check_specified", operatorAction: "Close and secure trailer doors." },
  "71":  { description: "Bad F2 or F3 Fuse", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Check and replace fuses." },
  "78":  { description: "Check SV1 Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "80":  { description: "Check SV3 Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "81":  { description: "Check FHR Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "82":  { description: "Check Remote Out of Range Light", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "83":  { description: "Check Remote Defrost Light", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "84":  { description: "Check Remote Alarm Light", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "85":  { description: "Check UL1 Unloader", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "86":  { description: "Check UL2 Unloader", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "87":  { description: "Check Remote Heat Light", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "88":  { description: "Check Remote Cool Light", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "89":  { description: "Check Remote Auto Light", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "93":  { description: "Check Start Up Buzzer", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "97":  { description: "Check SV2 Circuit", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Otherwise report alarm at end of day." },
  "121": { description: "Check Ambient Air Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "122": { description: "Check Return Air Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "123": { description: "Check Supply Air Sensor", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "124": { description: "Check Defrost Termination Sensor 1", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "125": { description: "Check Compressor Discharge Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "126": { description: "Check Fuel Sensor Circuit", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "129": { description: "Check Engine Coolant Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "130": { description: "Check Engine RPM Sensor", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "132": { description: "Check Defrost Termination Sensor 2", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "133": { description: "Check Remote Temperature Sensor 1", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "134": { description: "Check Remote Temperature Sensor 2", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "135": { description: "Check Remote Temperature Sensor 3", severity: "check_specified", operatorAction: "Manually monitor temperature. Report alarm at end of day." },
  "223": { description: "Engine Maintenance Due", severity: "check_specified", operatorAction: "Schedule engine maintenance service." },
  "225": { description: "General Maintenance Due", severity: "check_specified", operatorAction: "Schedule general maintenance service." },
  "226": { description: "Service Soon — PM 1 Due", severity: "check_specified", operatorAction: "Schedule PM 1 service." },
  "227": { description: "Service Soon — PM 2 Due", severity: "check_specified", operatorAction: "Schedule PM 2 service." },
  "228": { description: "Service Soon — PM 3 Due", severity: "check_specified", operatorAction: "Schedule PM 3 service." },
  "229": { description: "Service Soon — PM 4 Due", severity: "check_specified", operatorAction: "Schedule PM 4 service." },
  "230": { description: "Service Soon — PM 5 Due", severity: "check_specified", operatorAction: "Schedule PM 5 service." },
  "232": { description: "Setpoint Error", severity: "check_specified", operatorAction: "Verify setpoint is correctly entered. Report alarm at end of day." },
  "233": { description: "Model Number Error", severity: "check_specified", operatorAction: "Report alarm at end of day. Contact service technician." },
  "234": { description: "Unit Serial Number Error", severity: "check_specified", operatorAction: "Report alarm at end of day. Contact service technician." },
  "235": { description: "Control Serial Number Error", severity: "check_specified", operatorAction: "Report alarm at end of day. Contact service technician." },
  "236": { description: "Trailer Number Error", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "237": { description: "Functional Parameters Error", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Controller configuration issue." },
  "238": { description: "Configurations 1 Error", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Controller configuration issue." },
  "239": { description: "Configurations 2 Error", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Controller configuration issue." },
  "240": { description: "Hour Meter Error", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "241": { description: "Alarm Status Error", severity: "check_specified", operatorAction: "Report alarm at end of day." },
  "242": { description: "Discharge Pressure Calibration Error", severity: "check_specified", operatorAction: "Report alarm at end of day. Sensor calibration required." },
  "243": { description: "Suction Evaporator Calibration Error", severity: "check_specified", operatorAction: "Report alarm at end of day. Sensor calibration required." },
  "245": { description: "Micro Software Revision Error", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Software issue." },
  "246": { description: "EEPROM Write Failure", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Controller fault." },
  "247": { description: "Configurations 3 Error", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Controller configuration issue." },
  "248": { description: "Config Mode HP2 Error", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Controller configuration issue." },
  "249": { description: "Microprocessor Error", severity: "immediate_action", operatorAction: "If unit is shut down repair immediately. Controller failure likely." },
}

export const CARRIER_PRETRIP_CODES: Record<string, { description: string; severity: 'immediate_action' | 'check_specified'; operatorAction: string }> = {
  "P141": { description: "Pretrip Stopped by User", severity: "check_specified", operatorAction: "Pretrip was manually stopped. Re-run pretrip test." },
  "P143": { description: "Check Clutch Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair clutch circuit before returning unit to service." },
  "P144": { description: "Check UL1 Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair UL1 unloader circuit before returning unit to service." },
  "P145": { description: "Check Speed Solenoid Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair speed solenoid circuit before returning unit to service." },
  "P148": { description: "Check SV1 Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair SV1 solenoid valve circuit before returning unit to service." },
  "P149": { description: "Check SV3 Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair SV3 solenoid valve circuit before returning unit to service." },
  "P150": { description: "Check SV4 Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair SV4 solenoid valve circuit before returning unit to service." },
  "P151": { description: "Check Glow Plug Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair glow plug circuit before returning unit to service." },
  "P152": { description: "Check Fuel Solenoid Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair fuel solenoid circuit before returning unit to service." },
  "P153": { description: "Check Return Air Sensor", severity: "immediate_action", operatorAction: "Pretrip failed. Repair or replace return air sensor before returning unit to service." },
  "P154": { description: "Check Supply Air Sensor", severity: "immediate_action", operatorAction: "Pretrip failed. Repair or replace supply air sensor before returning unit to service." },
  "P155": { description: "Check Coolant Temperature Sensor", severity: "immediate_action", operatorAction: "Pretrip failed. Repair or replace coolant temp sensor before returning unit to service." },
  "P156": { description: "Check Battery Voltage", severity: "immediate_action", operatorAction: "Pretrip failed. Check battery condition and charging system." },
  "P157": { description: "Check Battery Current", severity: "immediate_action", operatorAction: "Pretrip failed. Check charging system and battery current draw." },
  "P158": { description: "Check Ambient Air Sensor", severity: "immediate_action", operatorAction: "Pretrip failed. Repair or replace ambient air sensor before returning unit to service." },
  "P159": { description: "Check Defrost Termination Sensor 1", severity: "immediate_action", operatorAction: "Pretrip failed. Repair or replace defrost termination sensor before returning unit to service." },
  "P160": { description: "Check Discharge Temperature Sensor", severity: "immediate_action", operatorAction: "Pretrip failed. Repair or replace discharge temp sensor before returning unit to service." },
  "P164": { description: "Check UL2 Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. Repair UL2 unloader circuit before returning unit to service." },
  "P165": { description: "Cannot Pump Down", severity: "immediate_action", operatorAction: "Pretrip failed. Refrigeration system cannot pump down. EPA 608 certified technician required." },
  "P174": { description: "Check Low Speed RPM", severity: "immediate_action", operatorAction: "Pretrip failed. Engine not achieving correct low speed RPM. Repair before returning to service." },
  "P175": { description: "Check High Speed RPM", severity: "immediate_action", operatorAction: "Pretrip failed. Engine not achieving correct high speed RPM. Repair before returning to service." },
  "P178": { description: "Check UL1 Unloader", severity: "immediate_action", operatorAction: "Pretrip failed. UL1 unloader not functioning correctly. Repair before returning to service." },
  "P181": { description: "Check SV4 Valve", severity: "immediate_action", operatorAction: "Pretrip failed. SV4 solenoid valve not functioning. Repair before returning to service." },
  "P182": { description: "Check SV1 Valve", severity: "immediate_action", operatorAction: "Pretrip failed. SV1 solenoid valve not functioning. Repair before returning to service." },
  "P183": { description: "Check SV3 Valve", severity: "immediate_action", operatorAction: "Pretrip failed. SV3 solenoid valve not functioning. Repair before returning to service." },
  "P191": { description: "Check UL2 Unloader", severity: "immediate_action", operatorAction: "Pretrip failed. UL2 unloader not functioning correctly. Repair before returning to service." },
  "P192": { description: "Check SV2 Circuit", severity: "immediate_action", operatorAction: "Pretrip failed. SV2 solenoid valve circuit fault. Repair before returning to service." },
  "P194": { description: "High Suction Pressure", severity: "immediate_action", operatorAction: "Pretrip failed. High suction pressure detected. EPA 608 certified technician required." },
  "P195": { description: "Low Suction Pressure", severity: "immediate_action", operatorAction: "Pretrip failed. Low suction pressure detected. Check refrigerant charge. EPA 608 certified technician required." },
  "P196": { description: "High Discharge Pressure", severity: "immediate_action", operatorAction: "Pretrip failed. High discharge pressure detected. Check condenser and refrigerant system. EPA 608 certified technician required." },
  "P198": { description: "Low Discharge Pressure", severity: "immediate_action", operatorAction: "Pretrip failed. Low discharge pressure detected. Check refrigerant charge. EPA 608 certified technician required." },
  "P200": { description: "Check Front Cylinders", severity: "immediate_action", operatorAction: "Pretrip failed. Front cylinder capacity issue detected. Compressor inspection required." },
  "P201": { description: "Check Rear Cylinders", severity: "immediate_action", operatorAction: "Pretrip failed. Rear cylinder capacity issue detected. Compressor inspection required." },
  "P202": { description: "High Side Leak", severity: "immediate_action", operatorAction: "Pretrip failed. High side refrigerant leak detected. EPA 608 certified technician required immediately." },
  "P203": { description: "Check Discharge Check Valve", severity: "immediate_action", operatorAction: "Pretrip failed. Discharge check valve not functioning. Repair before returning to service." },
  "P204": { description: "Low Suction Pressure", severity: "immediate_action", operatorAction: "Pretrip failed. Low suction pressure. Check refrigerant charge. EPA 608 certified technician required." },
  "P205": { description: "Check Defrost Termination Sensor 2", severity: "immediate_action", operatorAction: "Pretrip failed. Defrost termination sensor 2 fault. Repair before returning to service." },
}

export const TK_DISCLAIMER = "Alarm code definitions sourced from Thermo King operator document TK 40933-8-CH Rev 15. Not all codes apply to all units. Always consult your company and official service documentation for final decisions."
