export interface LaborGuideItem {
  label: string
  book_min: number
  book_max: number
  mobile_min: number
  mobile_max: number
  requires_refrigeration: boolean
  shop_only: boolean
}

export const LABOR_GUIDE: LaborGuideItem[] = [
  { label: 'Adjust belts',                                          book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Adjust engine RPM',                                     book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Adjust RPM sensor only',                                book_min: 0.3, book_max: 0.3, mobile_min: 0.8,  mobile_max: 0.8,  requires_refrigeration: false, shop_only: false },
  { label: 'Adjust valves including cover',                         book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: false, shop_only: false },
  { label: 'Alternator R&R',                                        book_min: 1.0, book_max: 1.5, mobile_min: 1.5,  mobile_max: 2.25, requires_refrigeration: false, shop_only: false },
  { label: 'Automated pretrip and visual inspection',               book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Battery cables check and service',                      book_min: 0.3, book_max: 0.3, mobile_min: 0.8,  mobile_max: 0.8,  requires_refrigeration: false, shop_only: false },
  { label: 'Battery load test',                                     book_min: 0.2, book_max: 0.2, mobile_min: 0.7,  mobile_max: 0.7,  requires_refrigeration: false, shop_only: false },
  { label: 'Battery R&R',                                           book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Belt R&R fan drive',                                    book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Charging system check',                                 book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Check and add oil and coolant',                         book_min: 0.3, book_max: 0.3, mobile_min: 0.8,  mobile_max: 0.8,  requires_refrigeration: false, shop_only: false },
  { label: 'Check for oil leak',                                    book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Complete PM service',                                   book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Compressor head R&R — one head',                        book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: false, shop_only: false },
  { label: 'Compressor heads R&R — both',                           book_min: 1.5, book_max: 1.5, mobile_min: 2.0,  mobile_max: 2.25, requires_refrigeration: false, shop_only: false },
  { label: 'Compressor inspection',                                 book_min: 0.7, book_max: 0.7, mobile_min: 1.2,  mobile_max: 1.2,  requires_refrigeration: false, shop_only: false },
  { label: 'Compressor major overhaul on bench',                    book_min: 6.0, book_max: 6.0, mobile_min: 0,    mobile_max: 0,    requires_refrigeration: false, shop_only: true  },
  { label: 'Compressor oil change including pump down',             book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: true,  shop_only: false },
  { label: 'Compressor R&R',                                        book_min: 3.0, book_max: 3.0, mobile_min: 3.5,  mobile_max: 4.0,  requires_refrigeration: true,  shop_only: false },
  { label: 'Compressor seal R&R',                                   book_min: 2.5, book_max: 2.5, mobile_min: 3.0,  mobile_max: 3.25, requires_refrigeration: true,  shop_only: false },
  { label: 'Compressor shaft seal R&R',                             book_min: 2.5, book_max: 2.5, mobile_min: 3.0,  mobile_max: 3.25, requires_refrigeration: true,  shop_only: false },
  { label: 'Condenser coil R&R',                                    book_min: 2.0, book_max: 2.0, mobile_min: 2.5,  mobile_max: 2.75, requires_refrigeration: true,  shop_only: false },
  { label: 'Condenser fan R&R',                                     book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: false, shop_only: false },
  { label: 'Coolant drain and refill',                              book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Coolant system flush — contaminated',                   book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Coolant system pressure test',                          book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Coupling R&R',                                          book_min: 2.0, book_max: 2.0, mobile_min: 2.5,  mobile_max: 2.75, requires_refrigeration: false, shop_only: false },
  { label: 'Datalogger download',                                   book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Defrost drain tubes clean',                             book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Diagnostic fee — standard',                             book_min: 1.0, book_max: 1.0, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Engine front drive pulley R&R',                         book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: false, shop_only: false },
  { label: 'Engine mount R&R — all',                                book_min: 2.0, book_max: 2.0, mobile_min: 2.5,  mobile_max: 2.75, requires_refrigeration: false, shop_only: false },
  { label: 'Engine on floor R&R',                                   book_min: 5.0, book_max: 5.0, mobile_min: 6.0,  mobile_max: 7.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Engine RPM sensor R&R including adjustment',            book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Engine thermostat R&R',                                 book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Evaporator coil R&R',                                   book_min: 3.0, book_max: 3.0, mobile_min: 4.0,  mobile_max: 5.0,  requires_refrigeration: true,  shop_only: false },
  { label: 'Evaporator fan blower R&R',                             book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: false, shop_only: false },
  { label: 'Evaporator wash out',                                   book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Expansion valve R&R',                                   book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Filter drier R&R including pump down',                  book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: true,  shop_only: false },
  { label: 'Fuel conditioner add',                                  book_min: 0.3, book_max: 0.3, mobile_min: 0.8,  mobile_max: 0.8,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel filter base R&R including filters and hoses',      book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Fuel filters R&R',                                      book_min: 0.3, book_max: 0.3, mobile_min: 0.8,  mobile_max: 0.8,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel leak check',                                       book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel line R&R — each',                                  book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel prime and start',                                  book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel primer pump R&R',                                  book_min: 0.4, book_max: 0.4, mobile_min: 0.9,  mobile_max: 0.9,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel solenoid R&R',                                     book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel system losing prime — check',                      book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Fuel system thaw out',                                  book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 2.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel transfer pump R&R',                                book_min: 0.8, book_max: 0.8, mobile_min: 1.3,  mobile_max: 1.5,  requires_refrigeration: false, shop_only: false },
  { label: 'Fuel transfer pump screen clean',                       book_min: 0.3, book_max: 0.3, mobile_min: 0.8,  mobile_max: 0.8,  requires_refrigeration: false, shop_only: false },
  { label: 'Glow plug R&R — each',                                  book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Glow plugs R&R — all',                                  book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Head gasket R&R and adjust valves',                     book_min: 5.0, book_max: 5.0, mobile_min: 10.0, mobile_max: 14.0, requires_refrigeration: false, shop_only: false },
  { label: 'Idler pulley R&R including belt adjustment',            book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Install new unit and check',                            book_min: 1.5, book_max: 1.5, mobile_min: 2.0,  mobile_max: 2.25, requires_refrigeration: false, shop_only: false },
  { label: 'Leak check full — recovery repair evacuate recharge',   book_min: 2.0, book_max: 2.0, mobile_min: 2.5,  mobile_max: 2.75, requires_refrigeration: true,  shop_only: false },
  { label: 'Leak check — recovery repair evacuate recharge',        book_min: 1.8, book_max: 1.8, mobile_min: 2.3,  mobile_max: 2.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Liquid line valve / king valve R&R',                    book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Low charge — leak check add charge',                    book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Main wire harness R&R',                                 book_min: 1.0, book_max: 2.5, mobile_min: 1.5,  mobile_max: 3.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Manual pretrip inspection',                             book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Microprocessor controller R&R',                         book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Oil change and filter',                                 book_min: 0.7, book_max: 0.7, mobile_min: 1.2,  mobile_max: 1.2,  requires_refrigeration: false, shop_only: false },
  { label: 'Oil filter spin-on R&R',                                book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Oil pressure switch R&R',                               book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Pilot solenoid R&R — complete job (incl. refrigeration)', book_min: 0.5, book_max: 0.5, mobile_min: 3.3, mobile_max: 4.3, requires_refrigeration: false, shop_only: false },
  { label: 'Pressure switch R&R — high/low/CFP',                   book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Radiator cap R&R',                                      book_min: 0.3, book_max: 0.3, mobile_min: 0.8,  mobile_max: 0.8,  requires_refrigeration: false, shop_only: false },
  { label: 'Radiator condenser wash out',                           book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Radiator hose R&R',                                     book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Radiator R&R including drain and refill',               book_min: 2.0, book_max: 2.0, mobile_min: 2.5,  mobile_max: 2.75, requires_refrigeration: false, shop_only: false },
  { label: 'Rear engine main seal R&R',                             book_min: 6.0, book_max: 6.0, mobile_min: 6.5,  mobile_max: 7.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Receiver tank R&R',                                     book_min: 1.5, book_max: 1.5, mobile_min: 2.0,  mobile_max: 2.25, requires_refrigeration: true,  shop_only: false },
  { label: 'Refrigerant line broken — repair',                      book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Relay board assembly R&R',                              book_min: 0.7, book_max: 0.7, mobile_min: 1.2,  mobile_max: 1.2,  requires_refrigeration: false, shop_only: false },
  { label: 'Relay R&R — any',                                       book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Return air sensor R&R',                                 book_min: 0.8, book_max: 0.8, mobile_min: 1.3,  mobile_max: 1.3,  requires_refrigeration: false, shop_only: false },
  { label: 'Road call fee',                                         book_min: 0.5, book_max: 1.0, mobile_min: 0.5,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'RPM sensor R&R including adjustment',                   book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Run and check operation',                               book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Safety valve R&R',                                      book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Sight glass R&R',                                       book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Solenoid coil R&R',                                     book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Speed solenoid — fuel R&R',                             book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Starter R&R',                                           book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Starter rebuild — not including R&R',                   book_min: 1.5, book_max: 1.5, mobile_min: 2.0,  mobile_max: 2.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Starter solenoid R&R on bench',                         book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Steam clean unit',                                      book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Suction solenoid valve R&R',                            book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Supply air sensor R&R',                                 book_min: 0.8, book_max: 0.8, mobile_min: 1.3,  mobile_max: 1.3,  requires_refrigeration: false, shop_only: false },
  { label: 'System pump down procedure and testing',                book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: true,  shop_only: false },
  { label: 'Three way valve R&R — complete job (incl. refrigeration)', book_min: 1.0, book_max: 2.0, mobile_min: 3.8, mobile_max: 4.8, requires_refrigeration: false, shop_only: false },
  { label: 'Throttling valve R&R',                                  book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Unit R&R',                                              book_min: 0.8, book_max: 0.8, mobile_min: 1.3,  mobile_max: 1.3,  requires_refrigeration: false, shop_only: false },
  { label: 'Unit remove',                                           book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Valve cover and gasket R&R',                            book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: false, shop_only: false },
  { label: 'Vibrasorber discharge R&R',                             book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Vibrasorber suction R&R',                               book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Vibrasorbers both R&R',                                 book_min: 1.5, book_max: 1.5, mobile_min: 2.5,  mobile_max: 2.5,  requires_refrigeration: true,  shop_only: false },
  { label: 'Voltage regulator R&R',                                 book_min: 0.8, book_max: 0.8, mobile_min: 1.3,  mobile_max: 1.3,  requires_refrigeration: false, shop_only: false },
  { label: 'Water pump R&R — standard engine',                      book_min: 4.0, book_max: 4.0, mobile_min: 4.5,  mobile_max: 5.0,  requires_refrigeration: false, shop_only: false },
  { label: 'Water pump R&R — Yanmar',                               book_min: 2.0, book_max: 2.0, mobile_min: 2.5,  mobile_max: 2.75, requires_refrigeration: false, shop_only: false },
  { label: 'Water temp sending unit R&R',                           book_min: 1.0, book_max: 1.0, mobile_min: 1.5,  mobile_max: 1.75, requires_refrigeration: false, shop_only: false },
  { label: 'Water temp switch R&R',                                 book_min: 0.5, book_max: 0.5, mobile_min: 1.0,  mobile_max: 1.0,  requires_refrigeration: false, shop_only: false },
]
